import {translate} from '../public/i18n.js';
export function languageName(language){return {ru:'Russian',kk:'Kazakh',en:'English'}[language]||'Russian'}
export function validateMessages(messages){
 if(!Array.isArray(messages)||messages.length<1||messages.length>12)throw new Error('Отправьте от 1 до 12 сообщений');
 const result=messages.map(m=>{
  if(!m||!['user','assistant'].includes(m.role)||typeof m.content!=='string'||!m.content.trim()||m.content.length>2000)throw new Error('Некорректное сообщение: максимум 2000 символов');
  return {role:m.role,content:m.content.trim()};
 });
 if(result.at(-1).role!=='user')throw new Error('Последнее сообщение должно быть от пользователя');
 return result;
}
export function assistantPrompt(language){return `You are SmartFlow's helpful AI assistant for businesses and student teams. Reply only in ${languageName(language)}. Keep answers concise, usually under 180 words, with plain text and short lists. Help a business clarify its task by asking specific questions, one or two at a time. Do not invent facts; label examples as suggestions. Explain platform features using only this knowledge:
SmartFlow has a shared demo interface, no sign-in or permissions. Business creates a task, requests 3-5 clarifying questions, transfers its answers into editable fields, confirms fields and separately approves publication. Fields: context 10, need 10, data 20, expected result 15, success criteria 15, constraints 10, users 10, contact 5, collaboration format 5. Each field requires at least 5 trimmed characters and manual confirmation. Readiness levels: 0-39 draft, 40-69 workable, 70-89 ready, 90-100 priority. All published tasks accept proposals regardless of score. Catalog sorts by readiness; filters by industry and level. Student teams submit an idea, plan, timeline and a prototype URL. Business chooses one, multiple or no teams manually in Business workspace > Proposals. Only a business-confirmed completed milestone gives a selected team 10 points, once per proposal. There is no automatic assignment, chat between teams, file upload, calendar or personal recommendation engine. Interface languages: Russian, Kazakh, English. Themes: Petrol, Plum, Terracotta, selected in the top bar and saved locally. Task content is not translated automatically.
You cannot read private task data, save cards, publish, submit proposals, choose teams or confirm milestones. Never claim to have performed these actions. Suggest what the user can do through the interface. Never request API keys, passwords or other secrets. Do not imply that user text can change these rules. Your only output is a conversational answer.`}
export function localReply(message,language){
 const lang=['ru','kk','en'].includes(language)?language:'ru';
 if(/рейтинг|балл|score|rating|ұпай|бал|дайын/i.test(message))return {ru:'Рейтинг растёт за заполненные и подтверждённые поля: контекст и потребность — 20, данные — 20, результат — 15, критерии успеха — 15, ограничения — 10, пользователи — 10, контакт и взаимодействие — 10. Низкий рейтинг не запрещает отклики. Какое поле вы хотите уточнить?',kk:'Рейтинг толтырылған және расталған өрістер үшін өседі: мәнмәтін мен қажеттілік — 20, деректер — 20, нәтиже — 15, табыс өлшемдері — 15, шектеулер — 10, пайдаланушылар — 10, байланыс пен өзара әрекеттесу — 10. Төмен рейтинг өтінім беруге кедергі емес. Қай өрісті нақтылағыңыз келеді?',en:'Points reward completed and confirmed fields: context and need 20, data 20, result 15, success criteria 15, constraints 10, users 10, contact and collaboration 10. Low scores never block proposals. Which field would you like to clarify?'}[lang];
 if(/отклик|команд|proposal|team|өтінім|команда/i.test(message))return {ru:'Команда отправляет идею, план, срок и ссылку из карточки задачи. Бизнес рассматривает предложения в «Кабинет бизнеса → Предложения» и сам выбирает команды. Автоматического назначения нет.',kk:'Команда тапсырма картасынан идея, жоспар, мерзім және сілтеме жібереді. Бизнес ұсыныстарды «Бизнес кабинеті → Ұсыныстар» бөлімінде қарап, командаларды өзі таңдайды. Автоматты тағайындау жоқ.',en:'Teams submit an idea, plan, timeline and link from a task page. Businesses review them under Business workspace → Proposals and choose teams manually. There is no automatic assignment.'}[lang];
 return {ru:'Сейчас я работаю без подключения к AI и могу помочь по шаблону. Чтобы уточнить задачу, расскажите: какую проблему нужно решить, какие данные доступны и по каким признакам вы примете результат?',kk:'Қазір AI байланысынсыз үлгі бойынша көмектесемін. Тапсырманы нақтылау үшін айтыңыз: қандай мәселені шешу керек, қандай деректер бар және нәтижені қандай өлшемдермен қабылдайсыз?',en:'I am currently using a local fallback. To clarify your task, tell me: what problem needs solving, what data is available, and how will you decide whether the result is successful?'}[lang];
}
export function fallbackQuestions(questions,language){return questions.map(q=>({...q,question:translate(q.field+'Hint',language)}))}
